version: "3.9"
 
services:
  streamlit:
    build: .                   # <- construye la imagen usando el Dockerfile en este directorio taxi_dashboard
    container_name: mundial_dashboard
    ports:
      - "8501:8501"

    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      
    env_file:
      - .env                   # carga tus secrets desde .env
    restart: unless-stopped
