version: "3.9"
 
services:
  streamlit:
    build: .                   # <- construye la imagen usando el Dockerfile en este directorio taxi_dashboard
    container_name: mundial_dashboard
    ports:
      - "8501:8501"
    env_file:
      - .env                   # carga tus secrets desde .env
    restart: unless-stopped
